services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'senha123'
      MYSQL_DATABASE: 'controlwise'
      MYSQL_ROOT_PASSWORD: 'senha123'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - C:\Users\leona\mysql:\var\lib\mysql